### ISSUE TITLE
No library in location src.boostface

### ISSUE THREAD

**Issue by CTOofjezt** [Atticuszz/BoostFace#23]
I've been searching everywhere, but the src/boostface directory isn't in the repository, even though it's referenced throughout the code. Could you please clarify what happened? Your project seems really interesting, and I'd love to try it out.

**Comment by Atticuszz** [comment]
> I've been searching everywhere, but the src/boostface directory isn't in the repository, even though it's referenced throughout the code. Could you please clarify what happened? Your project seems really interesting, and I'd love to try it out.
> 
> 
> 
> 
> 
> 
> 

Could you show what kind of function do you need? Cause some of code are in a mess, so I didn't upload to all😄

**Comment by CTOofjezt** [comment]
> > I've been searching everywhere, but the src/boostface directory isn't in the repository, even though it's referenced throughout the code. Could you please clarify what happened? Your project seems really interesting, and I'd love to try it out.
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> 
> Could you show what kind of function do you need? Cause some of code are in a mess, so I didn't upload to all😄

 I'm just trying to test the facial recognition part

**Comment by Atticuszz** [comment]
facial recognition has two parts,interfering scrfd onnx for detection and update tracker with sort algorithms
